config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    authenticated :user do
      root 'accounts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :accounts do

    member do
      get :deposite
      get :withdraw
      get :transfer
      get :statement

      post :make_deposite
      post :make_withdraw
      post :make_transfer
    end

  end

end

app/models/account.rb
class Account < ActiveRecord::Base
	#associations	
	belongs_to :user
	has_many :transactions, dependent: :destroy

	# validations
	validates :email, presence: true, email: true
	validates :phone, numericality: { only_integer: true }
	validates :phone, length: { is: 10 }
	validates :address, length: { maximum: 100,
    too_long: "%{count} characters is the maximum allowed" }
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	belongs_to :account
end

app/models/user.rb
class User < ActiveRecord::Base
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  layout "account", only: [:show, :deposite, :make_deposite, :withdraw, :make_withdraw, :transfer, :make_transfer, :statement]
  skip_before_filter :verify_authenticity_token, :only => [:index]
  include AccountsHelper

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def deposite
    @deposite = Transaction.new
  end

  # For deposite money
  def make_deposite
    if params[:transaction][:deposite_amount].to_i >= 1.0
      @dep = Transaction.create(account_id: params[:id], balance: params[:transaction][:deposite_amount], deposite_amount: params[:transaction][:deposite_amount])
      flash[:notice] = "Deposite successfully !"
      redirect_to account_url(params[:id])
    else 
       flash[:error] = "Please enter correct deposite amount "
      redirect_to request.referer
    end
  end

  def withdraw
    @withdraw = Transaction.new
  end

  # For withdraw money
  def make_withdraw
    if params[:transaction][:withdraw_amount].to_i >= 1.0 and current_balance(params[:id]).to_i > params[:transaction][:withdraw_amount].to_i
      @wid = Transaction.create(account_id: params[:id], withdraw_amount: params[:transaction][:withdraw_amount])
      flash[:notice] = "Withdraw successfully !"
      redirect_to account_url(params[:id])
    else 
       flash[:error] = "Please enter withdraw amount less than your current_balance Rs: #{current_balance(params[:id])}/-"
      redirect_to request.referer
    end
  end

  def transfer
    @transfer = Transaction.new
  end

  # For transfer money
  def make_transfer
    if params[:transaction][:transfer_amount].to_i > 1.0 and current_balance(params[:id]).to_i > params[:transaction][:transfer_amount].to_i
      @tran = Transaction.create(account_id: params[:id], transfer_amount: params[:transaction][:transfer_amount], reciever_account_id: params[:transaction][:reciever_account_id], sender_account_id: params[:id])
      flash[:notice] = "Transfer successfully !"
      redirect_to account_url(params[:id])
    else 
       flash[:error] = "Please enter transfer amount less than your current_balance Rs: #{current_balance(params[:id])}/-"
      redirect_to request.referer
    end
  end

  # To get Statements
  def statement
    @statements = Transaction.where("account_id = ?", params[:id]).order('created_at DESC').limit(10)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      # params.fetch(:account, {})
      params.require(:account).permit(:first_name, :last_name, :address, :phone,:email)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
	def current_balance(acc_no)
		dep_bal = Transaction.where("account_id = ? ", acc_no).sum(:deposite_amount)
		wid_bal = Transaction.where("account_id = ? ", acc_no).sum(:withdraw_amount)
		tran_bal = Transaction.where("account_id = ? ", acc_no).sum(:transfer_amount)

		bal = dep_bal - (wid_bal + tran_bal)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
        
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"><%= pluralize(@account.errors.count, "Error") %> prohibited this account from being saved:</h4>
            </div>
            <div class="modal-body">
              <ul>
                <% @account.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  <% end %>

  <div class="account">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3">
           <%= f.label :first_name, "First Name" %> 
        </div>
        <div class="col-md-4">
          <%= f.text_field :first_name, placeholder: "Enter First Name", required: true %>
        </div>
      </div>
    </div></br>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3">
           <%= f.label :last_name, "Last Name" %> 
        </div>
        <div class="col-md-4">
          <%= f.text_field :last_name, placeholder: "Enter Last Name", required: true %>
        </div>
      </div>
    </div></br>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3">
           <%= f.label :phone, "Phone No" %> 
        </div>
        <div class="col-md-4">
          <%= f.text_field :phone, placeholder: "Enter Phone No", required: true %>
        </div>
      </div>
    </div></br>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3">
           <%= f.label :email, "Email" %> 
        </div>
        <div class="col-md-4">
          <%= f.text_field :email, placeholder: "Enter Email", required: true %>
        </div>
      </div>
    </div></br>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3">
           <%= f.label :address, "Address" %> 
        </div>
        <div class="col-md-4">
          <%= f.text_area :address, placeholder: "Enter Address", required: true %>
        </div>
      </div>
    </div></br>

    
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3"></div>
        <div class="col-md-2">
          <div class="actions">
            <%= f.submit "Create Account", class:"btn btn-primary", style:"line-height: 2.8rem;" %>
          </div>
        </div>
        <div class="col-md-2">
          <%= link_to 'Accounts', accounts_path, class:"btn btn-primary",  style: "width: 100%;" %>
        </div>
      </div>
    </div>
  </div>

<% end %>

<script type="text/javascript">
    $(window).on('load',function(){
        $('#myModal').modal('show');
    });
</script>

app/views/accounts/deposite.html.erb
<%= form_for  @deposite, :url => make_deposite_account_path(params[:id]) do |f| %>

	<% if @deposite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deposite.errors.count, "error") %> prohibited this deposite from being saved:</h2>

      <ul>
      <% @deposite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


	<div class="account">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-4">
           <%= f.label :deposite_amount, " Enter The Deposite Amount" %> 
        </div>
        <div class="col-md-3">
          <%= f.text_field :deposite_amount, placeholder: "Enter amount you want to deposite", required: true %>
        </div>
      </div>
    </div></br>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3">
            <div class="actions">
              <%= f.submit "Deposite", class:"btn btn-primary", style:"line-height: 2.8rem;" %>
            </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/accounts/edit.html.erb
<h2>Editing Account</h2>

<%= render 'form' %>

app/views/accounts/index.html.erb
  <!-- <p id="notice"><%= notice %></p> -->
<div class="account">
  <h2> My Accounts</h2>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Account No</th>
        <th>First Name</th>
        <th>Last_Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @accounts.each do |account| %>
        <tr>
          <td><%= account.id %></td>
          <td><%= account.first_name %></td>
          <td><%= account.last_name %></td>
          <td><%= account.phone %></td>
          <td><%= account.email %></td>
          <td><%= account.address %></td>
          <td><%= link_to '', account, class:"fa fa-eye" %></td>
          <td><%= link_to '', edit_account_path(account), class:"fa fa-pencil" %></td>
          <td><%= link_to '', account, method: :delete, data: { confirm: 'Are you sure?' }, class:"fa fa-trash" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Account', new_account_path, class:"btn btn-primary" %>
</div>

app/views/accounts/new.html.erb
<h2>New Account</h2>

<%= render 'form' %>

app/views/accounts/show.html.erb
<div class="account_detail">
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-2">
				 Account No : 
			</div>
			<div class="col-md-3">
				<%= @account.id %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="col-md-2">
				 First Name : 
			</div>
			<div class="col-md-3">
				<%= @account.first_name %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="col-md-2">
				Last Name : 
			</div>
			<div class="col-md-3">
				<%= @account.last_name %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="col-md-2">
				 Phone No : 
			</div>
			<div class="col-md-3">
				<%= @account.phone %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="col-md-2">
				Email :
			</div>
			<div class="col-md-3">
				<%= @account.email %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="col-md-2">
				Address :  
			</div>
			<div class="col-md-3">
				<%= @account.address %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="col-md-2">
				 Current Balance : 
			</div>
			<div class="col-md-3">
				Rs. <%= current_balance(@account.id)%>
			</div>
		</div>
	</div>
</div>

app/views/accounts/statement.html.erb
  <p id="notice"><%= notice %></p>
  <div class="account">
    <div class="row">
      <div class="col-md-12">

        <h1>Statements</h1>

        <table class="table table-hover">
          <thead>
            <tr>
              <th>Account No</th>
              <th>Transaction Type</th>
              <th>Amount</th>
              <th>Transaction Date</th>
              <th>Payee Account No</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @statements.each do |statement| %>
              <tr>
                <td><%= statement.account_id %></td>

                <% if statement.deposite_amount > 0.00  %>
                  <td><%= "Deposite" %></td>
                <% elsif statement.withdraw_amount > 0.00 %>
                  <td><%= "Withdraw" %></td>
                <% elsif statement.transfer_amount > 0.00  %>
                  <td><%= "Transfer" %></td>
                <% end %>

                <% if statement.deposite_amount > 0.00 %>
                  <td><%= statement.deposite_amount %></td>
                <% elsif statement.withdraw_amount > 0.00 %>
                  <td><%= statement.withdraw_amount %></td>
                <% elsif statement.transfer_amount > 0.00  %>
                  <td><%= statement.transfer_amount %></td>
                <% end %>


                <td><%= statement.created_at.strftime('%d-%b-%Y %I:%M') %></td>

                <% if statement.transfer_amount > 0.00  %>
                  <td><%= statement.reciever_account_id %></td>
                <% else %>
                  <td><%= "---" %></td>
                <% end %>

                
              </tr>
            <% end %>
          </tbody>
        </table><br>

        
      </div>
    </div>
  </div>

app/views/accounts/transfer.html.erb
<%= form_for  @transfer, :url => make_transfer_account_path(params[:id]) do |f| %>

	<% if @transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% @transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="account">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-4">
          <%= f.label :reciever_account_id , "Account No To Transfer " %>
        </div>
        <div class="col-md-3">
        <%= f.text_field :reciever_account_id, placeholder: "Enter Account No", required: true %>
        </div>
      </div>
    </div></br>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-4">
          <%= f.label :transfer_amount %>
        </div>
        <div class="col-md-3">
          <%= f.text_field :transfer_amount, placeholder: "Enter amount you want to transfer", required: true %>
        </div>
      </div>
    </div></br>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3">
            <div class="actions">
              <%= f.submit "Transfer", class:"btn btn-primary", style:"line-height: 2.8rem;" %>
            </div>
        </div>
      </div>
    </div>
  </div>


 

<% end %>

app/views/accounts/withdraw.html.erb
<%= form_for  @withdraw, :url => make_withdraw_account_path(params[:id]) do |f| %>

	<% if @withdraw.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@withdraw.errors.count, "error") %> prohibited this withdraw from being saved:</h2>

      <ul>
      <% @withdraw.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="account">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-4">
           <%= f.label :withdraw_amount, " Enter The Withdraw Amount" %> 
        </div>
        <div class="col-md-3">
          <%= f.text_field :withdraw_amount, placeholder: "Enter amount you want to withdraw", required: true %>
        </div>
      </div>
    </div></br>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-3">
            <div class="actions">
              <%= f.submit "Withdraw", class:"btn btn-primary", style:"line-height: 2.8rem;" %>
            </div>
        </div>
      </div>
    </div>
  </div>
  	
<% end %>

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BankAccManagement" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Bank Account Management</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
         <!--  <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul> -->
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Signed in as  #{current_user.email}", "" %></li>
              <li><%= link_to "  Sign out", destroy_user_session_path, :method => :delete, class:"fa fa-sign-out" %></li>
            <% else %>
              <li><%= link_to "  Sign In", new_user_session_path, class:"fa fa-sign-in" %> </li>
              <li><%= link_to "  Sign up", new_user_registration_path, class:"fa fa-sign-up" %> </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3 acc_sidebar">
          <% if current_user %>
            <h3>Bank Transactions</h3>
            <ul class="nav nav-list">
              <!-- <li class="nav-header">Sidebar</li> -->
              <li><%= link_to "Deposite", deposite_account_path(params[:id])  %></li>
              <li><%= link_to "Withdraw", withdraw_account_path(params[:id])  %></li>
              <li><%= link_to "Transfer", transfer_account_path(params[:id])  %></li>
              <li><%= link_to "Statements", statement_account_path(params[:id])  %></li>
              <li><%= link_to "My Accounts", accounts_path  %></li>
            </ul>
          <% end %>

          <div  style="padding-top: 20px;font-size: 18px;color: green;">Current Balance </br>Rs: <span id="current_balance"><%= current_balance(params[:id]) %>/-</span></div>

          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <!-- <footer>
        <p>&copy; Company 2017</p>
      </footer> -->

    </div> <!-- /container -->

  </body>
</html>

<script type="text/javascript">
  $(document).ready(function(){
    setInterval(function(){
        $("#current_balance").fadeToggle(1000);
    }, 1500);
  });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BankAccManagement" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Bank Account Management</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <!-- <li><%#= link_to "Link1", "/path1"  %></li>
            <li><%#= link_to "Link2", "/path2"  %></li>
            <li><%#= link_to "Link3", "/path3"  %></li> -->
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Signed in as  #{current_user.email}", "" %></li>
              <li><%= link_to "  Sign out", destroy_user_session_path, :method => :delete, class:"fa fa-sign-out" %></li>
            <% else %>
              <li><%= link_to "  Sign In", new_user_session_path, class:"fa fa-sign-in" %> </li>
              <li><%= link_to "  Sign up", new_user_registration_path, class:"fa fa-sign-up" %> </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

      <!-- <footer>
        <p>&copy; Company 2017</p>
      </footer> -->

    </div> <!-- /container -->

  </body>
</html>